### ISSUE TITLE
womp womp

### ISSUE THREAD

**Issue by Hlebuw3k** [xoxfaby/BetterUI#188]
uh oh, time to be a crybaby

**Comment by Epsynus** [comment]
Oh be quiet, your kind of harassment is the reason were in this situation in the first place.

There was no reason for all those mods that removed the button in the first place, because it wasn't distracting or annoying and the developer even was open to moving it or making it hidden after people had seen it, but instead of contributing to the project with something like that, you people just started harassing the person instead.

Shame on you! Shame on you all!

**Comment by aqvoid** [comment]
actually, it is really sad where this is going..

**Comment by Hlebuw3k** [comment]
> Oh be quiet, your kind of harassment is the reason were in this situation in the first place.
> 
> There was no reason for all those mods that removed the button in the first place, because it wasn't distracting or annoying and the developer even was open to moving it or making it hidden after people had seen it, but instead of contributing to the project with something like that, you people just started harassing the person instead.
> 
> Shame on you! Shame on you all!

I don't care what the issue was, or what people did, I'm just a regular player trying to enjoy the game. And one day just launching the game and having a mod not work is the worst. From what I read, the mod maker was actively against removing the button, and changing the mod to include ONLY the button and nothing else only supports that view.
