### ISSUE TITLE
[Suggestion] Item count

### ISSUE THREAD

**Issue by MightyW0lf** [xoxfaby/BetterUI#2]
Show total item count in Tab scoreboard.

* Show count of items of each rarity.
* Don't include (or configurable option to not include) invisible/notier items.

**Comment by xoxfaby** [comment]
Thank you for your suggestion, this was actually one of the things I had planned for the mod, alongs side other small changes to the scoreboard,  I just haven't gotten to it yet. With StatsDisplay done I can probably start working on it. You can expect it to be as configurable as the rest of the mod.

If there are any more specific suggestions about item counters or scoreboard improvements, feel free to put them in here.

**Comment by MightyW0lf** [comment]
Something like "total item score", which would be basically total item count, except each rarity could have its own weight. So white items would add 1 to the score, meanwhile e.g. green items would add 2.

* Score for each tier would be configurable.
* Even configurable score per-item? That sounds like an overkill tho.

We're using ItemCounters mod (which counts invisible/notier items as well btw, which is why i mentioned it earlier) to decide who should pick some items in some scenarios (the one with lowest amount of items has priority). So in our case, this could be more accurate, since sometimes the user who has the least amount of items has e.g. a lot of red ones because they've used cauldron a few times.

**Comment by xoxfaby** [comment]
The problem is that score-per-item is subjective and also subject to change if items get buffed/nerfed. This wouldn't be a problem if the config system available to me wasn't so poor but maybe I can find a way to implement it. 

Score based on tier would be very easy though. Probably something like 6 for red, 2 for green, 1 for white? 3or4 for yellow and 1 for lunar? ( i usually like to keep lunar out of the consideration since the person essentially paid for it. 

Right now I'm mostly thinking about how to implement it together with my other scoreboard improvements I have in mind ( like moving the money counter to the left to make more space for the item counter.

**Comment by Cerbiac** [comment]
This "weighted item count" that accounts for score-per-item should have the ability to display next to unweighted so one can say "Darn, they have 50 items" with the unweighted, but "They only has 60 items-worth of stuff with all those whites, he should take the legendary to catch-up" with the weighted one.

On top of that, per-tier counters should have a setting for sort order, whether descending, ascending, or it's own unique order (latter-most would be most customizable, however niche)

**Comment by xoxfaby** [comment]
What do you mean by per-tier?

**Comment by brnnnrsmssn** [comment]
i think that means that an individual counter for each item-tier would be shown 5x(white), 2x(green), 1x(red). so you can quickly see how many of each tier of items. this would be nice when adjacent to total count:
43+2 (25, 15, 2, 1) = total+blue (white, green, red, yellow).

i agree that blue should be distinct from the other items because their acquisition is different and their stats often incur penalties of some sort.

i think the sort order for the per-tier count should match the inventory sort, if enabled.
